name: Build, and running Cypress Integration Test on push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Clone
      uses: actions/checkout@master
    - name: Install npm dependencies  
      uses: actions/npm@master
      with:
        args: install
    - name: Cypress Tests
      uses: bartlett705/npm-cy@6fa505d818d66409f91d1f42e3b15d50a0cc4886
      with:
        args: run ci   
    - name: Send Push Notification
      uses: techulus/push-github-action@master
      env:
        API_KEY: ${{ secrets.techulus_api_key }}
        MESSAGE: updated by Github Actions pipeline!
